name: C:\Users\Shawn\Desktop\gold_prediction\env
channels:
  - msys2
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - cython
  - scipy
  - pystan
  - fbprophet
  - widgetsnbextension
  - ipywidgets
  - IPython
  - scikit-learn
